#dataset: "NYU" # "kitti", "kitti_360"
dataset: "NYU"

n_relations: 4

enable_log: false


NYU_root: '/ssd/jenny/SSC/dataloaders/sscnet.cs.princeton.edu/sscnet_release/data/depthbin/'
NYU_preprocess_root: '/ssd/lyding/datasets/monoscene/'
logdir: '/ssd/lyding/datasets/monoscene/'


fp_loss: true 
frustum_size: 8 
batch_size: 1
n_gpus: 1
num_workers_per_gpu: 3 
exp_prefix: "exp"
run: 1
lr: 1e-4
weight_decay: 1e-4 

context_prior: true

relation_loss: true 
CE_ssc_loss: true
sem_scal_loss: true
geo_scal_loss: true

project_1_2: true
project_1_4: true
project_1_8: true




